name: Deploy to EC2 Instance
on:
  workflow_dispatch:
  push:
    branches:
      - ci/cd-debug
    paths-ignore:
      - README.md
      - .gitignore
concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Deploy to EC2
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              cd /home/ec2-user/verify
              set -e
              docker buildx version
              git pull origin main
              docker compose up --build -d

